# _config.yml for GitHub Pages site

title: Joanna Zolnik
description: A portfolio website of projects and thought provoking articles.
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
